### ISSUE TITLE
Page generated with autigen-<title> title

### ISSUE THREAD

**Issue by DexterMagnific** [sphinx-contrib/sphinxcontrib-confluencebuilder#130]
Hi,

Thank you a lot for this wonderful extension. I generated confluence pages from my sources, and some pages have autogen-<title> titles while others have the correct ones.

I checked the sources and in both cases the format used is the same (title + ===== underline).
Could you tell me how the page title is taken ? How to fix this issue ?

Thanks

**Comment by jdknight** [comment]
In the most recent release (v0.9), the title value is determined by the first _title element_ found in the _first block_ with the exception that [comment blocks](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#comments) are skipped. Unfortunately, the process of finding the title value is limited in more complex reStructuredText-defined documents. For example, if a document has other invisible blocks (such as a [hyperlink target](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#hyperlink-targets) or [substitutions](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#substitution-references)), the processing will fail to see the title block.

There is an active pull request ("builder: improve document title fetching" #126) which addresses the above issue (and additional scenarios where a document contains "Structural" blocks before the first section's title entry). This fix should be available in a future release. If you are looking to try it out ahead of time. you are welcome to try using this feature branch (`feature/improve-title-check`) to see if it resolves your issue (warning: has not been reviewed yet):
```
python -m pip install --user --upgrade git+https://github.com/tonybaloney/sphinxcontrib-confluencebuilder@feature/improve-title-check
```

It should not matter what character types you are using as long as your are following reStructuredText's documentation (which docutils follows, then Sphinx to this extension).

If you want to share an example leading portion of a document which has its title being automatically generated (if you are able), I can make sure it is working in #126 (and can make addition changes if needed to handle the use case).

**Comment by DexterMagnific** [comment]
Thank you for the reply. I do not use any of the strange constructs in my document.

If you want to try my build, just download QSvgStyle (https://github.com/DexterMagnific/QSvgStyle.git) and build the doc with your confluence backend. You'll notice that some pages have correct titles, while others have autogen ones, with no apparent reason (at least to me).
Thanks

**Comment by jdknight** [comment]
@DexterMagnific, thanks! I love example sets to check against.

Unfortunately, what you are experiencing is what I suspected. The documentation set appears to generate warnings for the following documents:

```
WARNING: document will be published using an generated title value: index
WARNING: document will be published using an generated title value: intro
WARNING: document will be published using an generated title value: qsvgstyle-engine
```

The `index` document fails to find a title since (in the current release), it stops checking for a title after seeing the `.. _contents:` reference. In `intro` and `qsvgstyle-engine` stop checking for a title after seeing the `.. highlight::` directive. Both cases show a limitation in at least v0.9 release of this extension.

I am happy you brought this up, since I believed the future title fetch improvements (#126) would have resolved this, only to still see it fail. The newer implementation relied on checking a series of node types to skip before looking for a section node -- an idea that is flawed in practice (the updated pull request indicates why). I have update the #126 to perform a must simpler title fetching attempt -- inspection shows it properly fetching expected titles in your documentation set.

This correction should be available in next release.

**Comment by DexterMagnific** [comment]
Thank you very much for your fast reply. This is fantastic you were able to fix it quickly. 
Hope you'll be able to add image upload support. This is the most feature I miss in your great backend.

**Comment by DexterMagnific** [comment]
Hi,

Seems fixed with my docs. Thanks a lot !

**Comment by jdknight** [comment]
Version 1.0 of this extension has been released which includes title corrections discussed in this issue; closing.
