### ISSUE TITLE
password in conf.py options

### ISSUE THREAD

**Issue by drafter250** [sphinx-contrib/sphinxcontrib-confluencebuilder#96]
I heard about this project on a Recent Talk Python podcast and was excited to try it out. Thanks for this Project!
In many organisations they use their LDAP passwords to login to confluence wiki. I dont think putting passwords in the conf.py is a good thing to encourage as many people include conf.py in their repo's. I think including a path variable to a password file is a better option no?

**Comment by jdknight** [comment]
@drafter250,

I don't think there's an intent to encourage users to place plain text password (let alone any other encoded, etc. password value) into a committed repository. The configuration and tutorial examples just talk about configuring the value `confluence_server_pass` for a password/API token. Nothing stops an individual from extending their configuration to retrieve a password from either an environment variable or an external file (we actually do [environment variable passing](https://github.com/tonybaloney/sphinxcontrib-confluencebuilder/blob/2d694c5bebab8e53bc50e4d6e6c964d7a5dbf783/test/test_publisher.py#L50) and [external file passing](https://github.com/tonybaloney/sphinxcontrib-confluencebuilder/blob/2d694c5bebab8e53bc50e4d6e6c964d7a5dbf783/test/test_publisher.py#L95-L104) of a password value in our publishing tests).

I do not think the security of the password/API key was attempted to managed by this extension. I don't know if we would want to introduce official environment variables or special files since (I feel) there could be various user scenarios where some authentications work and some do not. If there's a standard/common way to deal with authentication in Python programs that you'd suggest we consider, I'd be willing to take a look (I've only really worked in a limited scope in the Python world).

That being said, I wouldn't be opposed to add additional notes in our documentation to inform the user on not recommending to store plain text/encoded passwords in their own repositories.

**Comment by nklapste** [comment]
I used `getpass.getpass()` in my `conf.py` for creating a simple manual runtime confluence password prompt to fill in `confluence_server_pass` on starting a sphinx build. It may not be the most automated solution, but I found it worked effectively for minimum release projects. This could be a simple (yet limited) recommendation to implement into a `conf.py` for not using plain text passwords in projects.

**Comment by GhostofGoes** [comment]
Doing the same as @nklapste in a project, works fine as a workaround.

**Comment by digulla** [comment]
I think a simple example how to load a user/password combination from a file in the user's home folder would be great.
Using env variables is a security risk; they are visible to everyone on the same computer.

**Comment by tonybaloney** [comment]
I can add an example for a credential store like Hashicorp Vault?

**Comment by digulla** [comment]
Here is another solution using a JSON formatted file in the home folder as `dev/sphinx/sphinx-demo.json` of the user running Sphinx:

    import json
    def readUserPass():
        '''The JSON file must contain an array with two strings: User and password.'''
        with open(expanduser('~/dev/sphinx/sphinx-demo.json'), encoding='UTF-8') as fh:
            return json.load(fh)

Just paste the code above into your `conf.py`. You can then use the new function like so:

    confluence_server_user, confluence_server_pass = readUserPass()

The JSON file must look like this:

    ["user", "password"]

**Comment by jhermann** [comment]
Few people know that requests *automagically* uses `~/.netrc` when no explicit credentials are provided.  That could be mentioned in the docs, under the related password setting.

**Comment by jdknight** [comment]
Version 1.0 of this extension has been released with this change; closing this issue.
